service: sls

custom:
  settings:
    POSTS_TABLE: posts

provider:
  name: aws
  runtime: nodejs10.x
  environment: ${self:custom.settings}
  region: eu-central-1
  iamRoleStatements: 
    - Effect: "Allow"
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:customs.settings.POSTS_TABLE}"

functions:
  createPost:
    handler: handler.createPost
    events: 
    - http: 
        path: /post
        method: post

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AtributeDefinitions: 
          - AtributeName: "id"
            AtributeType: "S"
        KeySchema:
          - AtributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapasityUnits: 1
          WriteCapasityUnits: 1
          TableName: ${self:customs.settings.POSTS_TABLE}
